### ISSUE TITLE
Using role will `become: true` tries to create a local folder under that assumed identity.

### ISSUE THREAD

**Issue by cans** [cans/user-make#6]
There is a task, delegated to the local machine, that if the role is used as follows in a playbook, will try to create a folder locally, under the assumed identity:
```yaml
- hosts: servers
  roles:
     - role: "cans.user-make"
       become: true
       usermake_users:
         - name: alice
```

The bug is actually twofolds:

- that task should not "become";
- the `when:` condition is always true as a generator is not expanded into a possibly empty list, which is what we actually want to test.
